# Generated by Django 3.0.7 on 2020-07-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='occupation',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
